### ISSUE TITLE
Do not clear cookies if they do not exist in the first place

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-go#13]
Refer to supertokens/supertokens-node#17

**Comment by jscyo** [comment]
#### There is a race condition:

- Request1 is fired
- Request2 is fired
- Request1 creates a session
- Request2 calls getSession to check if a session exists
- Request1 returns cookies to the frontend
- Request2 clears cookies since the session does not exist
- The user is left with no session

#### To prevent the race condition the following changes need to be made:
- You need to remove the call to ``clearSessionFromCookie()`` in the [GetSession](https://github.com/supertokens/supertokens-go/blob/master/supertokens/supertokens.go#L137) function when the ``idRefreshToken`` from the cookie is ``nil``.
 -  You need to remove the call to ``clearSessionFromCookie()`` in the [RefreshSession](https://github.com/supertokens/supertokens-go/blob/master/supertokens/supertokens.go#L219) function when the ``inputRefreshToken`` from the cookie is ``nil``.

#### Add the following tests
- test that ``GetSession`` does not clear cookies if a session does not exist in the first place similar to the test found [here](https://github.com/supertokens/supertokens-node/blob/master/test/sessionExpress.test.js#L1128)
- test that ``RefreshSession`` does not clear cookies if a session does not exist in the first place similar to the test found [here](https://github.com/supertokens/supertokens-node/blob/master/test/sessionExpress.test.js#L1167)

**Comment by EnzoBtv** [comment]
Hey @jscyo I'm looking for projects to contribute. Can I get this issue?

**Comment by rishabhpoddar** [comment]
Hey @EnzoBtv sure! I have assigned this issue to you. 

Please fork from and send a PR to branch `1.4`

**Comment by EnzoBtv** [comment]
Made it!

**Comment by EnzoBtv** [comment]
Can you add to the PR the hacktoberfest-accepted label to help me? :)

**Comment by rishabhpoddar** [comment]
@EnzoBtv done!
